PKGDIR		?= ../..
L4DIR		?= $(PKGDIR)/../..

TARGET		= $(PKGNAME)

# list your .c or .cc files here
SRC_C = 
SRC_CC = main.cc

# list requirements of your program here
REQUIRES_LIBS   = libstdc++

include $(L4DIR)/mk/prog.mk
